

name: dummy
description: Just a dummy sensor

dependencies: []

outputs:
  - name: rpm
    address: tcp://*:6969

options:
  - name: numSensors
    type: int
    mutable: false
    default: 2
  - name: dummyMin
    type: int
    mutable: true
    default: 0
  - name: dummyMax
    type: int
    mutable: true
    default: 100